language: python

os:
  - linux
  - osx

python:
  - "2.7"
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - libhdf4-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./.travis/install_osx_miniconda.bash; fi

# command to run tests
script:
  - ./runexamples.sh
  - nosetests -v

notifications:
  email:
    recipients:
      - fshahriar@gmail.com
    on_success: never
    on_failure: change
