#!/usr/bin/env python

import sys
import Numeric

from mpy import *

MPY_Init()
rank = MPY_Comm_rank()
size = MPY_Comm_size()

root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, MPY_Get_processor_name())
MPY_Barrier()

if rank == 0:
    s = Numeric.array(((1,2,3),(4,5,6),(7,8,9)), 'f')
    r = MPY_Sendrecv_replace(s, 1, source=3, dataType=MPY_PYTHON_ARRAY)
    print "P%d" % rank, r

elif rank == 1:
    s = Numeric.array(((10,11,12),(13,14,15),(16,17,18)),'f')
    r = MPY_Sendrecv_replace(s, 2, source=0, dataType=MPY_PYTHON_ARRAY)
    print "P%d" % rank, r

elif rank == 2:
    s = Numeric.zeros((3,3),'f')
    r = MPY_Sendrecv_replace(s, 3, source=1, dataType=MPY_PYTHON_ARRAY)
    print "P%d" % rank, r

elif rank == 3:
    s = Numeric.ones((3,3),'f')
    r = MPY_Sendrecv_replace(s, 0, source=2, dataType=MPY_PYTHON_ARRAY)
    print "P%d" % rank, r
    
