#!/usr/bin/env python

import sys

from mpy import *

MPY_Init()
rank = MPY_Comm_rank()
size = MPY_Comm_size()
root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, MPY_Get_processor_name())

MPY_Barrier()

# Gathered messages can be of different lengths.

msgs = {0: ["0 to 0",    "0 to 1",    "0 to 2",    "0 to 3"],
        1: ["1 to -0",   "1 to -1",   "1 to -2",   "1 to -3"],
        2: ["2 to --0",  "2 to --1",  "2 to --2",  "2 to --3"],
        3: ["3 to ---0", "3 to ---1", "3 to ---2", "3 to ---3"]}
        
res1 = MPY_Alltoallv(msgs[rank])
print "P%d MPY_Alltoallv res1=%s" % (rank, res1)
MPY_Barrier()
        
# This time we gather messages transmitted using MPI datatypes.
msgs = {0: [ 0,            1, 2, (3,4)],
        1: [(9,10),       11,12, (13,14,15)],
        2: [(18,19,20),   21,22, (23,24,25,26)],
        3: [(27,28,29,30),31,32, (33,34,35,36,37)]}

res2 = MPY_Alltoallv(msgs[rank], dataType=MPY_FLOAT)
print "P%d MPY_Alltoallv res2=%s" % (rank, res2)

MPY_Finalize()
