#!/usr/bin/env python

import sys
import Numeric

from mpy import *

MPY_Init()
rank = MPY_Comm_rank()
size = MPY_Comm_size()

root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, MPY_Get_processor_name())
MPY_Barrier()


# We use a maximum count of 100 for the received count. The worst that can
# happen is that some memory is (temporarily) wasted.
if rank == 0:
    s = ['from 0 to 1', 1,2,'andre',[3.14,-5.2]]
    r = MPY_Sendrecv(s, 1, source=2, recvCount=100)
    print "P%d" % rank, r

elif rank == 1:
    # Pickling Numeric arrays is costly.
    s = Numeric.array(((1,2,3),(4,5,6),(7,8,9)), 'i')
    r = MPY_Sendrecv(s, 2, source=0, recvCount=100)
    print "P%d" % rank, r

elif rank == 2:
    s = '01234567890123456789'
    r = MPY_Sendrecv(s, 0, source=1, recvCount=100)
    print "P%d" % rank, r

    
