#!/usr/bin/env python

import sys
import Numeric

from mpy import *

MPY_Init()
rank = MPY_Comm_rank()
size = MPY_Comm_size()
root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, MPY_Get_processor_name())

MPY_Barrier()

arr = Numeric.array(((rank-1, rank, rank+1),
                     (1-rank, 2-rank, 3-rank)), 'i')

# IMPORTANT :  the root participates in the reduce operation.

res1 = MPY_Reduce(arr, MPY_MIN, root, dataType=MPY_PYTHON_ARRAY)
res2 = MPY_Reduce(arr, MPY_MAX, root, dataType=MPY_PYTHON_ARRAY)
res3 = MPY_Reduce(arr, MPY_SUM, root, dataType=MPY_PYTHON_ARRAY)
if rank == root:
    print "P%d  MIN=\n%s" % (rank, res1)
    print "P%d  MAX=\n%s" % (rank, res2)
    print "P%d  SUM=\n%s" % (rank, res3)

MPY_Finalize()
