#!/usr/bin/env python

import sys
import Numeric

from mpy import *

MPY_Init()
rank = MPY_Comm_rank()
size = MPY_Comm_size()
root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, MPY_Get_processor_name())

MPY_Barrier()

v1 = Numeric.array(((rank+100,rank+101,rank+102,rank+103),
                    (rank+200,rank+201,rank+202,rank+203),
                    (rank+300,rank+301,rank+302,rank+303),
                    (rank+400,rank+401,rank+402,rank+403)), 'i')

# Each process receives a segment of 4 values.
res1 = MPY_Scan(v1, MPY_MIN, dataType=MPY_PYTHON_ARRAY)
print "P%d MIN=%s" % (rank, res1)
MPY_Barrier()
res2 = MPY_Scan(v1, MPY_MAX, dataType=MPY_PYTHON_ARRAY)
print "P%d MAX=%s" % (rank, res2)
MPY_Barrier()
res3 = MPY_Scan(v1, MPY_SUM, dataType=MPY_PYTHON_ARRAY)
print "P%d SUM=%s" % (rank, res3)


MPY_Barrier()
        
MPY_Finalize()
