#!/usr/bin/env python

import sys

from mpy import *

MPY_Init()
rank = MPY_Comm_rank()
size = MPY_Comm_size()
root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, MPY_Get_processor_name())
MPY_Barrier()

v1 = range(rank, rank+3)
print "P%d v1=%s" % (rank, v1)
res1 = MPY_Scan(v1, MPY_MAX)
print "P%d MPY_Scan res1=%s" % (rank, res1)
MPY_Barrier()
        
# This time we use MPI datatypes.
v2 = range(100*rank, 100*rank+4)
print "P%d v2=%s" % (rank, v2)
res2 = MPY_Scan(v2, MPY_SUM, dataType=MPY_FLOAT)
print "P%d MPY_Scan res2=%s" % (rank, res2)

MPY_Finalize()
