#!/usr/bin/env python

import sys
import Numeric

from mpy import *

MPY_Init()
rank = MPY_Comm_rank()
size = MPY_Comm_size()

root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, MPY_Get_processor_name())
MPY_Barrier()


if rank == 0:
    s = Numeric.zeros((3,3),'i')
    d = Numeric.zeros((4,4), 'f')
    r = MPY_Sendrecv(s, 1, source=2, sendDataType=MPY_PYTHON_ARRAY,
                     recvDataType=MPY_PYTHON_ARRAY, array=d)
    print "P%d" % rank, r

elif rank == 1:
    s = Numeric.array(((1,2,3),(4,5,6),(7,8,9)), 'i')
    d = Numeric.zeros((3,3), 'i')
    r = MPY_Sendrecv(s, 2, source=0, sendDataType=MPY_PYTHON_ARRAY,
                     recvDataType=MPY_PYTHON_ARRAY, array=d)
    print "P%d" % rank, r

elif rank == 2:
    s = Numeric.ones((4,4), 'f')
    d = Numeric.zeros((3,3), 'i')
    r = MPY_Sendrecv(s, 0, source=1, sendDataType=MPY_PYTHON_ARRAY,
                     recvDataType=MPY_PYTHON_ARRAY, array=d)
    print "P%d" % rank, r

    
