#!/usr/bin/env python

import sys

from mpy import *

MPY_Init()
rank = MPY_Comm_rank()
size = MPY_Comm_size()
root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, MPY_Get_processor_name())

MPY_Barrier()

# All gathered messages must be of the same length. Using MPY_Allgather() with
# messages transmitted as python objects is risky, since it may be
# hard to guarantee that the strings used to encapsulate the objects
# will be of the same length. It is better to use MPY_Allgatherv() instead.
v1 = range(rank, rank + 3)
res1 = MPY_Allgather(v1)
print "P%d res1=%s" % (rank, res1)
MPY_Barrier()
        
# This time we gather messages transmitted using MPI datatypes.
v2= range(10*rank, 10*rank+2)
res2 = MPY_Allgather(v2, dataType=MPY_FLOAT)
print "P%d res2=%s" % (rank, res2)

MPY_Finalize()
