#!/usr/bin/env python

import sys
import mpi
import Numeric
import time

mpi.init()
rank = mpi.comm_rank()
size = mpi.comm_size()

root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, mpi.get_processor_name())
mpi.barrier()

toProc = [1, 3]

if rank == 0:
    requests = []
    for dst in toProc:
        requests.append(mpi.isend('message #1 for process %d' % dst, dst))
        requests.append(mpi.isend('message #2 for process %d' % dst, dst))
        requests.append(mpi.isend('message #3 for process %d' % dst, dst))
    while True:
        idx = mpi.waitsome(requests)
        if idx is None:
            break
        print "P%d %d requests (%s) completed" % (rank, len(idx), idx)

elif rank in toProc:
    requests = []
    requests.append(mpi.irecv(0))
    requests.append(mpi.irecv(0))
    requests.append(mpi.irecv(0))
    n = 0
    while True:
        idx, status = mpi.waitsome(requests, retStatus=True)
        if idx is None:
            break
        print "P%d %d requests (%s) completed" % (rank, len(idx), idx)
        for n in idx:
            obj = mpi.requestExtract(requests[n])
            print "P%d obj=" % rank, obj, "status=",status
        
