#!/usr/bin/env python

import sys
import Numeric

from mpy import *

MPY_Init()
rank = MPY_Comm_rank()
size = MPY_Comm_size()
root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, MPY_Get_processor_name())

MPY_Barrier()

# Each process starts with a different array.
arr = Numeric.array(((rank-1, rank, rank+1),
                     (1-rank, 2-rank, 3-rank)), 'i')

res1 = MPY_Allreduce(arr, MPY_MIN, dataType=MPY_PYTHON_ARRAY)
res2 = MPY_Allreduce(arr, MPY_MAX, dataType=MPY_PYTHON_ARRAY)
res3 = MPY_Allreduce(arr, MPY_SUM, dataType=MPY_PYTHON_ARRAY)

print "P%d  MIN=\n%s" % (rank, res1)
print "P%d  MAX=\n%s" % (rank, res2)
print "P%d  SUM=\n%s" % (rank, res3)

MPY_Finalize()
