#!/usr/bin/env python

import sys
import Numeric

from mpy import *

MPY_Init()
rank = MPY_Comm_rank()
size = MPY_Comm_size()

root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, MPY_Get_processor_name())
MPY_Barrier()

toProc = [1,2,3]
numMes = 3

if rank == root:
    requests = []
    for num in range(numMes):
        for p in toProc:
            msg = "from %d to %d msg #%d" % (rank, p, num)
            requests.append(MPY_Isend(msg, p))
            print "P%d immediate send mes #%d to %d" % (rank, num, p)
    while True:
        idx = MPY_Waitany(requests)
        if idx is None:
            break
        print "P%d request %d complete" % (rank, idx)
    

elif rank in toProc:
    requests = []
    for num in range(numMes):
        requests.append(MPY_Irecv(root, 1000))
    while True:
        idx, status = MPY_Waitany(requests, retStatus=True)
        if idx is None:
            break
        msg = requestExtract(requests[idx])
        print "P%d request %d complete msg='%s' status=%s" % (rank, idx, msg, status)
    
