#!/usr/bin/env python

import sys
import math

import Numeric

from mpy import *

MPY_Init()
rank = MPY_Comm_rank()
size = MPY_Comm_size()
root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, MPY_Get_processor_name())

MPY_Barrier()

a1 = Numeric.zeros(3, 'f')
a2 = Numeric.zeros((2,2), 'i')

for k in range(1,3):
    if rank == root:
        b1 = MPY_Bcast(root, Numeric.array((10*k,10*k+1,10*k+2),'f'),
                       dataType=MPY_PYTHON_ARRAY)
        b2 = MPY_Bcast(root, Numeric.array(((20*k,20*k+1),(20*k+2,20*k+3)), 'i'),
                       dataType=MPY_PYTHON_ARRAY)

    else:
        b1 = MPY_Bcast(root, dataType=MPY_PYTHON_ARRAY, array=a1)
        b2 = MPY_Bcast(root, dataType=MPY_PYTHON_ARRAY, array=a2)
        
    print "P%d iteration %d \nb1=\n%s \nb2=\n%s" % (rank, k, b1, b2)

    MPY_Barrier()

MPY_Finalize()
