#!/usr/bin/env python

import sys

from mpy import *

MPY_Init()

rank = MPY_Comm_rank()
size = MPY_Comm_size()

cartComm = MPY_Cart_create(MPY_COMM_WORLD, (2, 2))

if rank == 0:
    # Let MPI suggest optimal cartesian dimensions
    print "nnodes=6 dims=(0,0)   -> %s" % MPY_Dims_create(6, (0,0))
    print "nnodes=7 dims=(0,0)   -> %s" % MPY_Dims_create(7, (0,0))
    print "nnodes=6 dims=(0,3,0) -> %s" % MPY_Dims_create(6, (0,3,0))
    # Following call is erroneous : 7 is not a multiple of 3.
    #print "nnodes=7 dims=(0,3,0) -> %s" % MPY_Dims_create(7, (0,3,0))

    print "cartComm topology=%d" % MPY_Topo_test(cartComm)
    print "MPY_COMM_WORLD topology=%d" % MPY_Topo_test(MPY_COMM_WORLD)

    print "cartComm ndims=%s" % MPY_Cartdim_get(cartComm)

    print "cartComm (0,0) -> rank %d" % MPY_Cart_rank(cartComm, (0,0))
    print "cartComm (0,1) -> rank %d" % MPY_Cart_rank(cartComm, (0,1))
    print "cartComm (1,0) -> rank %d" % MPY_Cart_rank(cartComm, (1,0))
    print "cartComm (1,1) -> rank %d" % MPY_Cart_rank(cartComm, (1,1))

    for n in range(size):
        print "cartComm rank %d -> %s" % (n, MPY_Cart_coords(cartComm, n))


info = MPY_Cart_get(cartComm)
print "P%s cartComm info dims=%s periods=%s coords=%s" % \
          (rank, info[0], info[1], info[2])

src, dst = MPY_Cart_shift(cartComm, 0, 1)
print "P%d shift dimension=0 direction=1, src=%d dst=%d" % \
      (rank, src, dst)
src, dst = MPY_Cart_shift(cartComm, 0, -1)
print "P%d shift dimension=0 direction=-1, src=%d dst=%d" % \
      (rank, src, dst)
src, dst = MPY_Cart_shift(cartComm, 1, 1)
print "P%d shift dimension=1 direction=1, src=%d dst=%d" % \
      (rank, src, dst)
src, dst = MPY_Cart_shift(cartComm, 1, -1)
print "P%d shift dimension=1 direction=-1, src=%d dst=%d" % \
      (rank, src, dst)

commsub0 = MPY_Cart_sub(cartComm, (1,0))
commsub1 = MPY_Cart_sub(cartComm, (0,1))
info = MPY_Cart_get(commsub0)
print "P%s commsub0 info dims=%s periods=%s coords=%s" % \
          (rank, info[0], info[1], info[2])
info = MPY_Cart_get(commsub1)
print "P%s commsub1 info dims=%s periods=%s coords=%s" % \
          (rank, info[0], info[1], info[2])

print "P%d cart_map() = %d" % (rank, MPY_Cart_map(MPY_COMM_WORLD, (1,1)))

graphComm = MPY_Graph_create(MPY_COMM_WORLD, (2,3,4,6),(1,3,0,3,0,2))
nNodes, nEdges = MPY_Graphdims_get(graphComm)
print "P%d graphComm nNodes=%d nEdges=%d" % (rank, nNodes, nEdges)
index, edges = MPY_Graph_get(graphComm)
print "P%d graphComm index=%s edges=%s" % (rank, index, edges)
print "P%d graphComm nNeighbors=%d neighbors=%s" % \
      (rank, MPY_Graph_neighbors_count(graphComm, rank),
       MPY_Graph_neighbors(graphComm, rank))
print "P%d graph_map=%d" % \
      (rank, MPY_Graph_map(MPY_COMM_WORLD, (2,3,4,6),(1,3,0,3,0,2)))


MPY_Finalize()

