#!/usr/bin/env python

import sys

from mpy import *

MPY_Init()
rank = MPY_Comm_rank()
size = MPY_Comm_size()

root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, MPY_Get_processor_name())
MPY_Barrier()

if rank == root:
    # IMPORTANT :  the root participates in the scatter operation,
    # and sends a message to itself.

    # All scattered messages must be of the same length, except if dataType
    # MPY_PYTHON_OBJ is used.
    msgSeq = []
    for k in range(size):
        msgSeq.append(range(k, k+5))
    res = MPY_Scatter(root, msgSeq, dataType=MPY_FLOAT)
else:
    res = MPY_Scatter(root, dataType=MPY_FLOAT)

print "P%d received '%s'" % (rank, res)
MPY_Barrier()

# Now we use default dataType MPY_PYTHON_OBJ. Messages can be of different lengths.
if rank == root:
    msgSeq = [[1,2,3,'a'], [100,200,300,'ab'], 'abc', 'abcd']
    res = MPY_Scatter(root, msgSeq)
else:
    res = MPY_Scatter(root)

print "P%d received '%s'" % (rank, res)
MPY_Barrier()

MPY_Finalize()
