#!/usr/bin/env python

import sys
import mpi
import Numeric
import time

mpi.init()
rank = mpi.comm_rank()
size = mpi.comm_size()

root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, mpi.get_processor_name())
mpi.barrier()


if rank == 0:
    requests = []
    requests.append(mpi.isend('message #1 for process 3', 3))
    requests.append(mpi.isend('message #2 for process 3 bla bla bla', 3))
    requests.append(mpi.isend([i for i in range(1000,1010)], 3))

    # Stupid loop showing the use of testall().
    # waitall() is of course much more efficient.
    n = 0
    while True:
        n += 1
        flag = mpi.testall(requests)
        if flag:
            print "P%d all sends complete after %d tests" % (rank, n)
            break

elif rank == 3:
    requests = []
    requests.append(mpi.irecv(0))
    requests.append(mpi.irecv(0))
    requests.append(mpi.irecv(0))

    # Stupid loop again...
    n = 0
    while True:
        n += 1
        flag, status = mpi.testall(requests, True)
        if flag:
            print "P%d all recvs complete after %d tests" % (rank, n)
            for n in range(len(requests)):
                obj = mpi.requestExtract(requests[n])
                print "P%d received status #%d = %s obj=%s" % \
                      (rank, n, status[n], obj)
            break

        
