#!/usr/bin/env python

import sys
import mpi
import Numeric
import time

mpi.init()
rank = mpi.comm_rank()
size = mpi.comm_size()

root = 0

print "%.5f" % time.time(),"I am P%d of %d on node %s" % \
      (rank, size, mpi.get_processor_name())
mpi.barrier()

toProc = [1,2,3]
numMes = 3

if rank == root:
    # Create a permanent request for each receiver.
    requests = {}
    for p in toProc:
        requests[p] = mpi.rsend_init(10, p, dataType=mpi.MPI_SHORT)
    # Send messages using the permanent requests.
    app = []
    for num in range(numMes):
        for p in toProc:
            mpi.requestLoad(requests[p], range(10))
            # Start the send, equivalent to mpi.isend()
            mpi.start(requests[p])
            # Wait for request to complete.
            mpi.wait(requests[p])
            print "%.5f" % time.time(),"P%d  send complete to %d num %d" % \
                  (rank, p, num)

    print "%.5f" % time.time(),"P%d all msgs sent" % rank
    

elif rank in toProc:
    for num in range(numMes):
        msg, status = mpi.recv(root, dataType=mpi.MPI_SHORT, retStatus=True)
        print "%.5f" % time.time(),"P%d received '%s' status=%s" % \
              (rank, msg, status)
    
