#!/usr/bin/env python

import sys
import mpi
import Numeric

mpi.init()
rank = mpi.comm_rank()
size = mpi.comm_size()

root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, mpi.get_processor_name())
mpi.barrier()

toProc = [1,2,3]
numMes = 3

if rank == root:
    for num in range(numMes):
        for p in toProc:
            msg = "non-buffered send from %d to %d msg #%d" % (rank, p, num)
            mpi.send(msg, p)
    print "P%d all messages sent in non-buffered mode" % rank

    for p in toProc:
        msg, status = mpi.recv(p, retStatus=True)
        print "P%d received from %d msg='%s'" % \
              (rank, p, msg)
        
elif rank in toProc:
    for num in range(numMes):
        msg, status = mpi.recv(root, retStatus=True)
        print "P%d received from %d msg='%s'" % \
              (rank, root, msg)
    print "P%d all non-buffered messages received" % rank

    msg = "non-buffered send from %d to %d" % (rank, root)
    mpi.send(msg, root)
    print "P%d sent to %d msg='%s'" % (rank, root, msg)
