#!/usr/bin/env python

import sys

from mpy import *

MPY_Init()
rank = MPY_Comm_rank()
size = MPY_Comm_size()
root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, MPY_Get_processor_name())

MPY_Barrier()

# All gathered messages must be of the same length.

msgs = {0: ["from 0 to 0", "from 0 to 1", "from 0 to 2", "from 0 to 3"],
        1: ["from 1 to 0", "from 1 to 1", "from 1 to 2", "from 1 to 3"],
        2: ["from 2 to 0", "from 2 to 1", "from 2 to 2", "from 2 to 3"],
        3: ["from 3 to 0", "from 3 to 1", "from 3 to 2", "from 3 to 3"]}
        
res1 = MPY_Alltoall(msgs[rank])
print "P%d MPY_Alltoall res1=%s" % (rank, res1)
MPY_Barrier()
        
# This time we gather messages transmitted using MPI datatypes.
msgs = {0: [0, 1, 2, 3],
        1: [10,11,12,13],
        2: [20,21,22,23],
        3: [30,31,32,33]}

res2 = MPY_Alltoall(msgs[rank], dataType=MPY_FLOAT)
print "P%d MPY_Alltoall res2=%s" % (rank, res2)

MPY_Finalize()
