#!/usr/bin/env python

import sys
import mpi

mpi.init()
rank = mpi.comm_rank()
size = mpi.comm_size()

root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, mpi.get_processor_name())
mpi.barrier()

# LAM can buffer only one message. If 'nMes' is set to a value > 1,
# the program will deadlock.
nMes = 1

if rank == 0:
    for n in range(nMes):
        mpi.send("msg %d from 0 to 1" % n, 1)
    for n in range(nMes):
        msg = mpi.recv(1)
        print "P%d received '%s'" % (rank, msg)

elif rank == 1:
    for n in range(nMes):
        mpi.send("msg %d 1 from 1 to 0" % n, 0)
    for n in range(nMes):
        msg = mpi.recv(0)
        print "P%d received '%s'" % (rank, msg)
  



