#!/usr/bin/env python

import sys
import mpi
import Numeric
import time

mpi.init()
rank = mpi.comm_rank()
size = mpi.comm_size()

root = 0

print "I am P%d of %d on node %s" % \
      (rank, size, mpi.get_processor_name())
mpi.barrier()


if rank == 0:
    requests = []
    requests.append(mpi.isend('message #1 for process 3', 3))
    requests.append(mpi.isend('message #2 for process 3 bla bla bla', 3))
    requests.append(mpi.isend([i for i in range(1000,1010)], 3))
    status = mpi.waitall(requests, True)
    for n in range(len(status)):
        print "P%d sent status #%d = %s" % (rank, n, status[n]) 

elif rank == 3:
    requests = []
    requests.append(mpi.irecv(0))
    requests.append(mpi.irecv(0))
    requests.append(mpi.irecv(0))

    status = mpi.waitall(requests, True)
    for n in range(len(status)):
        obj = mpi.requestExtract(requests[n])
        print "P%d received status #%d = %s obj=%s" % (rank, n, status[n], obj) 

        
