#!/bin/sh

pydoc    pyhdf.HDF > pyhdf.HDF.txt
pydoc -w pyhdf.HDF 
pydoc    pyhdf.SD  > pyhdf.SD.txt
pydoc -w pyhdf.SD 
pydoc    pyhdf.VS  > pyhdf.VS.txt
pydoc -w pyhdf.VS
pydoc    pyhdf.V   > pyhdf.V.txt
pydoc -w pyhdf.V
