name: package into static linked wheel

on:
  push:
    tags:
    - 'v*' #

jobs:
    package:
        name: package up into a nice wheel
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2

        - uses: actions/setup-python@v2
          name: Install Python
          with:
            python-version: '3.7'

        - name: Install cibuildwheel
          run: |
            python -m pip install cibuildwheel==2.3.1

        - name: Build wheels for linux python versions
          run: |
            python -m cibuildwheel --output-dir dist
          env:
            CIBW_BUILD: '{cp,pp}3*-many*'
            CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
            CIBW_BEFORE_ALL_LINUX: yum -y install epel-release hdf hdf-devel && ln -s /usr/lib64/hdf/lib* /usr/lib64/
            CIBW_ARCHS_LINUX: 'x86_64'
        
        - name: purge old _linux_wheels
          run: |
            mkdir wheelhouse
            cp dist/*manylinux* wheelhouse/
        
        - name: create source distribution archive for pypi
          run: |
            python -m pip install numpy
            python setup.py sdist -d wheelhouse

        - uses: actions/upload-artifact@v2
          with:
            name: wheelhouse
            path: wheelhouse

        - name: Publish a Python distribution to Test PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            user: __token__
            password: ${{ secrets.PYPI_TEST_TOKEN }}
            repository_url: https://test.pypi.org/legacy/
            packages_dir: wheelhouse/
            verbose: true

        - name: Publish a Python distribution to PyPI
          if: github.event.base_ref == 'refs/heads/master'
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
            packages_dir: wheelhouse/


