name: package into static linked wheel

on: [push]


jobs:
    package:
        name: package up into a nice wheel
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2

        - name: Build manylinux Python wheels
          uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2014_x86_64
          with:
            python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39'
            system-packages: 'epel-release hdf hdf-devel'
            build-requirements: 'numpy'
            pre-build-command: 'ln -s /usr/lib64/hdf/lib* /usr/lib64/'
            package-path: ''
        
        - name: purge old _linux_wheels
          run: |
            mkdir wheelhouse
            cp dist/*manylinux* wheelhouse/
    
        - uses: actions/upload-artifact@v2
          with:
            name: wheelhouse
            path: wheelhouse

        - name: Publish a Python distribution to PyPI
          if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
            repository_url: https://test.pypi.org/legacy/
            packages_dir: wheelhouse/


